### ISSUE TITLE
Would you want to implement dynamic routers via the Controllers?

### ISSUE THREAD

**Issue by gpynes** [seanpmaxwell/overnight#3]
Hey Sean, love the package so far. I found it from one of your blog posts, so keep writing! 

I've been playing around with the package and one thing that caught my eye was the CustomRouter idea. I like the idea I just feel like since the Controller's implementation is based on which Router you end up using, adding the Router in the Server config blurs the single responsibility principle a bit. 

I was thinking maybe you could add a second argument or even config object to the Controller decorator that accepts the Router and then either in the Server.addControllers method or the private Server._getRouter method you could just use the router attached to the Controller. This would allow more flexibility I think. 

This is just a thought and I've only glanced over the src code, but if you think it's viable and useable I could submit a PR. Just let me know.

Thanks! And keep up the great work on this!

**Comment by seanpmaxwell** [comment]
I've never worked with custom routers so I'm not sure how people go about using them. I created that feature because I got request for it in a reddit post. When people use custom routers do they typically use it in combination with the default express router or as a full replacement? If you tell me it's common for people to use combinations of different router libs I could easily update the @Controller decorator to accept a second argument which is the type of router to be used for that specific controller.

**Comment by gpynes** [comment]
Hmm.. that's a fair point I could definitely be trying to solve an issue that's not really an issue. I've never really used both in tandem, so I'd be lying if I said it was common place but I do usually structure my apps like such where each module has it's own router that I bring in to my main server and setup the routes to each router that way. I could throw up an example if needed. 

I think I may be over complicating things with this feature request however and you're right until it's needed might not be need to be implemented. Closing for now thanks man!
